---
- name: Install and start Nginx
  hosts: localhost
  strategy: free
  become: true
  tasks:
    - name: Update the package index
      ansible.builtin.apt:
        update_cache: yes
    
    - name: Install Nginx
      ansible.builtin.apt:
        name: nginx
        state: present
    
    - name: Ensure Nginx is started and enabled
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: yes
